// <auto-generated />
namespace CctvStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fo));
        
        string IMigrationMetadata.Id
        {
            get { return "201511211141221_fo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
